fastlane_version "2.25.0"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    #increment_build_number
    gym(scheme: 'TranslatorApp', export_method: 'development')

    emails = values[:test_email] ? values[:test_email] : ['joshuacalpuerto@gmail.com', 'naickyserrano03@gmail.com', 'francolouie@gmail.com', 'r.schrooten1@gmail.com', 'testtranslatorapp@gmail.com', 'a.leferink@buurtzorgconcepten.nl', 'nicoschrooten@gmail.com', 'frankleensen@servicediensten.nu'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'df89ce09be99dc237431a51a24be9d1ed69edb75',
             build_secret: 'ff9937ec1703131548a778cce07ca5b87b775ee0ebb245876a1f624815040ee4',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end
